// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXNGCCnowq1uvR01n2SibzZStPxo9qF1U',
    appId: '1:900719762696:web:dd7ade86af82cdc8e6e0bd',
    messagingSenderId: '900719762696',
    projectId: 'her-safety',
    authDomain: 'her-safety.firebaseapp.com',
    storageBucket: 'her-safety.appspot.com',
    measurementId: 'G-6YPRM25GNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOFRMNaBrT35zQxcbJ1Xme5iK_a57Xzg8',
    appId: '1:900719762696:android:2f1bfba87e67a94ce6e0bd',
    messagingSenderId: '900719762696',
    projectId: 'her-safety',
    storageBucket: 'her-safety.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWWpk1s1H3LrR8opSIbj0YYyMSElv850Q',
    appId: '1:900719762696:ios:0f58c1dab6c50e45e6e0bd',
    messagingSenderId: '900719762696',
    projectId: 'her-safety',
    storageBucket: 'her-safety.appspot.com',
    iosBundleId: 'com.example.sample1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWWpk1s1H3LrR8opSIbj0YYyMSElv850Q',
    appId: '1:900719762696:ios:c9c53d7799d0060de6e0bd',
    messagingSenderId: '900719762696',
    projectId: 'her-safety',
    storageBucket: 'her-safety.appspot.com',
    iosBundleId: 'com.example.sample1.RunnerTests',
  );
}
